os: windows
language: shell
jobs:
  include:
    - stage: build
      script:
        - choco install dotnet-sdk
        - dotnet restore Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --source https://api.nuget.org/v3/index.json
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework netstandard2.1
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework netstandard2.0
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework net5.0
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework net6.0
    - stage: test
      script:
        - choco install dotnet-sdk
        - dotnet restore Hto3.SimpleSpecsDetector.TestNet60/Hto3.SimpleSpecsDetector.TestNet60.csproj --source https://api.nuget.org/v3/index.json
        - dotnet run --project Hto3.SimpleSpecsDetector.TestNet60/Hto3.SimpleSpecsDetector.TestNet60.csproj --framework net6.0