os: windows
language: shell
jobs:
  include:
    - stage: build
      script:
        - choco install dotnet-sdk
        - dotnet restore Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -f netstandard2.1
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -f netstandard2.0
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -f net5.0