os: windows
language: csharp
mono: none
dotnet: 5.0.203
jobs:
  include:
    - stage: build
      script:
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -f netstandard2.1
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -f netstandard2.0
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -f net5.0