os: windows
language: shell
jobs:
  include:
    - stage: build
      script:
        - choco install dotnet-sdk
        - dotnet restore Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --source https://api.nuget.org/v3/index.json
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework netstandard2.1
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework netstandard2.0
        - dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --framework net5.0
    - stage: test
      script:
        - choco install dotnet-sdk
        - dotnet restore Hto3.SimpleSpecsDetector.TestNet50/Hto3.SimpleSpecsDetector.TestNet50.csproj --source https://api.nuget.org/v3/index.json
        - dotnet run --project Hto3.SimpleSpecsDetector.TestNet50/Hto3.SimpleSpecsDetector.TestNet50.csproj --framework net5.0