name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet build Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj --configuration Release
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet run --project Hto3.SimpleSpecsDetector.TestNet100/Hto3.SimpleSpecsDetector.TestNet100.csproj --configuration Release
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet run --project Hto3.SimpleSpecsDetector.TestNet100/Hto3.SimpleSpecsDetector.TestNet100.csproj --configuration Release
  publish:
    name: Nuget Publish
    runs-on: windows-latest
    needs: [test-linux, test-windows]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet build -c Release Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj
      - run: dotnet pack --no-build -c Release Hto3.SimpleSpecsDetector/Hto3.SimpleSpecsDetector.csproj -o .
      - run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n